export const productsData = [
  // LÍNEA DESENGRASANTES
  {
    id: "EM-46-des",
    code: "EM-46",
    name: "EM-46",
    category: "desengrasantes",
    categoryName: "Línea Desengrasantes",
    tagline: "Diluyente para Asfalto - Petróleo - Grasas",
    uses: "En la limpieza de equipos viales, petroleras y equipos de perforación de petróleo, pisos de talleres, etc.",
    dilutions: "Usar puro para tareas pesadas. Diluir 1:10 con gas-oil para tareas livianas.",
    badges: ["Tareas Pesadas", "Petróleo & Asfalto", "Uso Vial"],
    icon: "fa-oil-can",
    featured: true
  },
  {
    id: "GALL-3",
    code: "GALL-3",
    name: "GALL-3",
    category: "desengrasantes",
    categoryName: "Línea Desengrasantes",
    tagline: "Desengrasante para Vajilla Concentrado",
    uses: "En el lavado de vajilla y cristalería de restaurantes, hoteles, confiterías, hospitales, etc.",
    dilutions: "1:200 con agua (contiene tensioactivos y abrillantadores sintéticos).",
    badges: ["Concentrado", "Tensioactivos Sintéticos", "Alto Rendimiento"],
    icon: "fa-utensils",
    featured: false
  },
  {
    id: "DT-15",
    code: "DT-15",
    name: "DT-15",
    category: "desengrasantes",
    categoryName: "Línea Desengrasantes",
    tagline: "Desengrasante para Frigoríficos Aprobado por SENASA",
    uses: "En la limpieza general de frigoríficos o establecimientos de industria cárnica o alimenticia.",
    dilutions: "1:100 con agua.",
    badges: ["Aprobación SENASA", "Industria Cárnica", "Inocuidad Alimenticia"],
    icon: "fa-drumstick-bite",
    featured: true
  },
  {
    id: "SOLWAT",
    code: "SOLWAT",
    name: "SOLWAT",
    category: "desengrasantes",
    categoryName: "Línea Desengrasantes",
    tagline: "Desengrasante Industrial Hidrosoluble",
    uses: "En la limpieza de máquinas y equipos, limpieza interior de tornos / rectificadoras, cocinas y campanas, surtidores de combustibles, etc.",
    dilutions: "Hasta 1:10 para limpieza pesada, y hasta 1:20 para repaso o limpieza liviana.",
    badges: ["Hidrosoluble", "Multiuso Industrial", "No Inflamable"],
    icon: "fa-gears",
    featured: true
  },
  {
    id: "X-02",
    code: "X-02",
    name: "X-02",
    category: "desengrasantes",
    categoryName: "Línea Desengrasantes",
    tagline: "Desengrasante Limpiador para Pisos Industriales",
    uses: "En la limpieza de pisos de talleres, industrias, estaciones de servicio, etc.",
    dilutions: "Desde 1:1 hasta 1:10 según el estado de la superficie a limpiar.",
    badges: ["Pisos de Taller", "Estaciones de Servicio", "Penetración Profunda"],
    icon: "fa-layer-group",
    featured: false
  },

  // LÍNEA AUTOMOTOR
  {
    id: "BRILLANTE",
    code: "BRILLANTE",
    name: "BRILLANTE",
    category: "automotor",
    categoryName: "Línea Automotor",
    tagline: "Shampoo Nueva Generación con Abrillantador Incorporado",
    uses: "En el lavado de vehículos. Con equipos automáticos o espumadoras manuales.",
    dilutions: "1:200 con agua (para lavado con espumadora o lavado manual).",
    badges: ["Nueva Generación", "Abrillantador Incorporado", "Espumadoras"],
    icon: "fa-spray-can-sparkles",
    featured: true
  },
  {
    id: "CERA-WAX",
    code: "CERA-WAX",
    name: "CERA-WAX",
    category: "automotor",
    categoryName: "Línea Automotor",
    tagline: "Cera Líquida Automotor & Escurridor",
    uses: "Acondicionador para vehículos y escurridor del agua de enjuague.",
    dilutions: "1:50 con agua para uso manual. Aplicación automática ver instrucciones del equipo.",
    badges: ["Efecto Escurridor", "Brillo Duradero", "Protección Carrocería"],
    icon: "fa-car",
    featured: false
  },
  {
    id: "MASTER",
    code: "MASTER",
    name: "MASTER",
    category: "automotor",
    categoryName: "Línea Automotor",
    tagline: "Micropelícula Monomolecular Antiestática / Protectora (Filtro UV)",
    uses: "En la protección y embellecimiento de superficies vidriadas o pintadas (automóviles - ventanales).",
    dilutions: "1:3 con agua (ver literatura técnica).",
    badges: ["Filtro UV", "Antiestático", "Protector Superficies"],
    icon: "fa-shield-halved",
    featured: true
  },
  {
    id: "HI-JOB",
    code: "HI-JOB",
    name: "HI-JOB",
    category: "automotor",
    categoryName: "Línea Automotor",
    tagline: "Lavacamiones para Servicio Pesado",
    uses: "En la limpieza de camiones: Chasis - Motores - Carrocerías.",
    dilutions: "1:20 a 1:100 con agua ó con agua y kerosene según el uso (ver literatura).",
    badges: ["Servicio Pesado", "Flotas & Camiones", "Desincruste de Chasis"],
    icon: "fa-truck-front",
    featured: false
  },
  {
    id: "RC-3M",
    code: "RC-3M",
    name: "RC-3M",
    category: "automotor",
    categoryName: "Línea Automotor",
    tagline: "Renovador Total de Cauchos y Plásticos del Automotor",
    uses: "En la terminación y embellecimiento del automotor. Uso interior y exterior.",
    dilutions: "Usar puro. Aplicar con esponja. Seca rápidamente, no deja residuos ni mancha.",
    badges: ["Secado Rápido", "Sin Residuos", "Uso Interior & Exterior"],
    icon: "fa-circle-notch",
    featured: false
  },
  {
    id: "GLASSNET",
    code: "GLASSNET",
    name: "GLASSNET",
    category: "automotor",
    categoryName: "Línea Automotor",
    tagline: "Limpiavidrios Antiestático",
    uses: "En la terminación de la limpieza, para limpiar vidrios, espejos, puertas de blindex, etc.",
    dilutions: "Usar puro con pulverizador a gatillo. Secar con papel absorbente o paño limpio.",
    badges: ["Antiestático", "Transparencia Total", "Gatillo Rápido"],
    icon: "fa-wand-magic-sparkles",
    featured: false
  },

  // LÍNEA INDUSTRIAL
  {
    id: "D-PHOS",
    code: "D-PHOS",
    name: "D-PHOS",
    category: "industrial",
    categoryName: "Línea Industrial",
    tagline: "Desoxidante - Desengrasante - Fosfatizante Concentrado",
    uses: "Tratamiento de chapas luego del mecanizado o estampado. Antes de recibir un acabado protector.",
    dilutions: "1:8 a 1:30 dependiendo de la velocidad deseada y temperatura del baño.",
    badges: ["Fosfatizante 3 en 1", "Metalurgia", "Prepintado"],
    icon: "fa-hammer",
    featured: true
  },
  {
    id: "ELECTROSOL",
    code: "ELECTROSOL",
    name: "ELECTROSOL",
    category: "industrial",
    categoryName: "Línea Industrial",
    tagline: "Solvente Dieléctrico de Alta Seguridad",
    uses: "Para la limpieza y descarbonizado de todos los elementos y equipos eléctricos.",
    dilutions: "Usar puro por sopleteado o inmersión.",
    badges: ["Solvente Dieléctrico", "Descarbonizante", "Seguridad Eléctrica"],
    icon: "fa-bolt-lightning",
    featured: true
  },
  {
    id: "EM-46-ind",
    code: "EM-46 (Industrial)",
    name: "EM-46",
    category: "industrial",
    categoryName: "Línea Industrial",
    tagline: "Diluyente para Asfalto - Petróleo - Grasas Pesadas",
    uses: "En la limpieza de equipos viales, petroleras y equipos de perforación de petróleo, pisos de talleres, etc.",
    dilutions: "Usar puro para tareas pesadas. Diluir 1:10 con gas-oil para tareas livianas.",
    badges: ["Equipos Viales", "Perforadoras", "Uso Pesado"],
    icon: "fa-oil-well",
    featured: false
  },
  {
    id: "NO-SHOCK",
    code: "NO-SHOCK",
    name: "NO-SHOCK",
    category: "industrial",
    categoryName: "Línea Industrial",
    tagline: "Repelente de Humedad para Equipos Eléctricos",
    uses: "Protector y deshumectante de equipos eléctricos, anticorrosivo y lubricante.",
    dilutions: "Usar puro por sopleteado o inmersión.",
    badges: ["Deshumectante", "Anticorrosivo", "Lubricante Dieléctrico"],
    icon: "fa-plug-circle-bolt",
    featured: false
  },
  {
    id: "SCALER-60",
    code: "SCALER-60",
    name: "SCALER-60",
    category: "industrial",
    categoryName: "Línea Industrial",
    tagline: "Desincrustante Químico para Torres de Enfriamiento y Calderas",
    uses: "Limpiador químico de incrustaciones calcáreas.",
    dilutions: "10% de la capacidad de los equipos (ver literatura técnica).",
    badges: ["Calderas", "Torres de Enfriamiento", "Anti-sarro"],
    icon: "fa-temperature-arrow-up",
    featured: false
  },
  {
    id: "SCALER-GEL",
    code: "SCALER-GEL",
    name: "SCALER-GEL",
    category: "industrial",
    categoryName: "Línea Industrial",
    tagline: "Desincrustante Gel Concentrado",
    uses: "En la limpieza de superficies verticales incrustadas de sarro (azulejos, sanitarios, lavaderos de autos, industria frigorífica, etc.).",
    dilutions: "Usar puro. El producto actúa mejor sobre superficies secas.",
    badges: ["Gel Vertical", "Fácil Adherencia", "Frigoríficos & Azulejos"],
    icon: "fa-bottle-droplet",
    featured: false
  },
  {
    id: "HOTLESS",
    code: "HOTLESS",
    name: "HOTLESS",
    category: "industrial",
    categoryName: "Línea Industrial",
    tagline: "Tratamiento de Agua en Torres de Enfriamiento",
    uses: "En torres y sistemas de refrigeración: Anti-incrustante / anti-corrosivo / alguicida.",
    dilutions: "4 litros por Tonelada de agua.",
    badges: ["Anti-corrosivo", "Alguicida", "Torres & Refrigeración"],
    icon: "fa-water",
    featured: false
  },

  // LÍNEA HOSPITALARIA
  {
    id: "KEMIA",
    code: "KEMIA",
    name: "KEMIA",
    category: "hospitalaria",
    categoryName: "Línea Hospitalaria",
    tagline: "Limpiador de Instrumental Quirúrgico",
    uses: "En la limpieza y mantenimiento de instrumental antes de llevar al autoclave.",
    dilutions: "1:30 a 1:50 según la severidad y antigüedad de la suciedad.",
    badges: ["Pre-Autoclave", "Instrumental Médico", "Alta Precisión"],
    icon: "fa-stethoscope",
    featured: true
  },
  {
    id: "SANITY",
    code: "SANITY",
    name: "SANITY",
    category: "hospitalaria",
    categoryName: "Línea Hospitalaria",
    tagline: "Limpiador Bactericida para Áreas de Seguridad Hospitalaria",
    uses: "En la limpieza y desinfección de quirófanos, salas de emergencias, traumatología, mesadas, piletas, picaportes y paredes azulejadas.",
    dilutions: "1:20 a 1:30 con agua.",
    badges: ["Bactericida", "Quirófanos & Emergencias", "Desinfección Crítica"],
    icon: "fa-notes-medical",
    featured: true
  },
  {
    id: "SCRATCH",
    code: "SCRATCH",
    name: "SCRATCH",
    category: "hospitalaria",
    categoryName: "Línea Hospitalaria",
    tagline: "Descontaminante para Quirófanos y Ambulancias",
    uses: "En la asepsia y descontaminación de quirófanos, ambulancias y áreas de seguridad.",
    dilutions: "Usar puro con fumigador eléctrico.",
    badges: ["Asepsia Total", "Fumigado Eléctrico", "Ambulancias"],
    icon: "fa-truck-medical",
    featured: false
  },
  {
    id: "SOFTLY-Q",
    code: "SOFTLY-Q",
    name: "SOFTLY-Q",
    category: "hospitalaria",
    categoryName: "Línea Hospitalaria",
    tagline: "Limpiamanos para Cirugía Concentrado",
    uses: "En la limpieza y asepsia de las manos del profesional, antes y después de la intervención.",
    dilutions: "1:3 con agua. Aplicar durante 3 a 5 minutos.",
    badges: ["Asepsia Profesional", "Cirugía", "Cuidado Dermatólogico"],
    icon: "fa-hands-bubbles",
    featured: false
  },
  {
    id: "CLOROSOL",
    code: "CLOROSOL CONCENTRADO",
    name: "CLOROSOL CONCENTRADO",
    category: "hospitalaria",
    categoryName: "Línea Hospitalaria",
    tagline: "Gel Limpiador Desinfectante con Cloro Active",
    uses: "En la limpieza y desinfección de oficinas, baños, vestuarios, plantas avícolas, hospitales, etc.",
    dilutions: "Hasta 1:100 con agua.",
    badges: ["Cloro Activo", "Gel Desinfectante", "Plantas Avícolas & Baños"],
    icon: "fa-pump-soap",
    featured: false
  },

  // LÍNEA ECOLÓGICA
  {
    id: "ECOGRASS",
    code: "ECOGRASS",
    name: "ECOGRASS",
    category: "ecologica",
    categoryName: "Línea Ecológica",
    tagline: "Desengrasante Emulsionable - Hidrosoluble / No Inflamable =ECOLÓGICO=",
    uses: "Limpieza de máquinas y equipos, trenes de laminación, tornos, prensas hidráulicas, balancines, cocinas, hornos, campanas, friteras, etc.",
    dilutions: "1:1 a 1:15 con agua según la suciedad y tipo de grasas o carbones a limpiar.",
    badges: ["Certificado Biodegradabilidad 99,5%", "No Inflamable", "Eco-Friendly", "Seguridad Laboral"],
    icon: "fa-leaf",
    featured: true
  }
];
